# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars_overall', models.IntegerField()),
                ('stars_speaker', models.IntegerField()),
                ('stars_content', models.IntegerField()),
                ('stars_relevance', models.IntegerField()),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('cinderella', 'Cinderella'), ('goldilocks', 'Goldilocks & the Three Bears'), ('hansel_gretel', 'Hanzel and Gretel'), ('snow_white', 'Snow White and the Seven Dwarves'), ('three_pigs', 'The Three Little Pigs')], max_length=100)),
                ('description', models.TextField()),
                ('time_and_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Workshop'),
        ),
    ]
