# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160705_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars_content',
            new_name='stars_characters',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='stars_speaker',
            new_name='stars_story',
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(choices=[('cinderella', 'Cinderella'), ('hansel_gretel', 'Hansel & Gretel'), ('rapunzel', 'Rapunzel'), ('snow_white', 'Snow White and the Seven Dwarfs'), ('three_pigs', 'The Three Little Pigs'), ('twelve_princesses', 'The 12 Dancing Princesses')], max_length=100),
        ),
    ]
